version: '3.9'

services:
  # Mongodb service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db

  # Node api service
  api:
    build: .
    ports:
      # local->container
      - 4000:4000
    environment:
      PORT: 4000
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: anshudb
    depends_on:
      - mongo_db
    volumes:
      - .:/mongowithexpress

  # Package watcher service
  package-watcher:
    image: node:latest
    command: sh -c "npm install -g chokidar-cli && chokidar '/mongowithexpress/package.json' -c 'npm install'"
    volumes:
      - .:/mongowithexpress
    depends_on:
      - api

volumes:
  mongo_data: {}
